import { Octokit } from "@octokit/rest";
import { PRContext, AIProvider, RepoConfig } from "./types.js";
import { logger } from "./logger.js";
import {
  Delivery,
  FileEdit,
  StackedPrOutcome,
  deliver,
  formatDeliveryReply,
} from "./stacked-pr.js";

export type { Delivery } from "./stacked-pr.js";
export type { StackedPrOutcome } from "./stacked-pr.js";

// ─── Helpers ──────────────────────────────────────────────────

function parseFileEdits(aiResponse: string): FileEdit[] | null {
  // Try to extract a JSON array from the response — the model may wrap it in
  // markdown fences or include surrounding prose.
  const jsonMatch = aiResponse.match(/\[[\s\S]*\]/);
  if (!jsonMatch) return null;

  try {
    const parsed = JSON.parse(jsonMatch[0]);
    if (!Array.isArray(parsed)) return null;

    const edits: FileEdit[] = [];
    for (const item of parsed) {
      if (
        typeof item === "object" &&
        item !== null &&
        typeof item.path === "string" &&
        typeof item.content === "string"
      ) {
        edits.push({ path: item.path, content: item.content });
      }
    }
    return edits.length > 0 ? edits : null;
  } catch {
    return null;
  }
}

async function getFileContent(
  octokit: Octokit,
  owner: string,
  repo: string,
  ref: string,
  path: string
): Promise<string | null> {
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path, ref });
    if (!Array.isArray(data) && "content" in data && data.encoding === "base64") {
      return Buffer.from(data.content, "base64").toString("utf-8");
    }
    return null;
  } catch {
    return null;
  }
}

function buildFileContext(files: { path: string; content: string | null; patch: string }[]): string {
  return files
    .map((f) => {
      if (f.content) {
        return `### ${f.path}\n\`\`\`\n${f.content}\n\`\`\``;
      }
      return `### ${f.path} (patch only)\n\`\`\`diff\n${f.patch}\n\`\`\``;
    })
    .join("\n\n");
}

async function gatherFullFiles(
  octokit: Octokit,
  context: PRContext
): Promise<{ path: string; content: string | null; patch: string }[]> {
  const results: { path: string; content: string | null; patch: string }[] = [];

  for (const file of context.files) {
    if (file.status === "removed") continue;
    const content = await getFileContent(
      octokit,
      context.owner,
      context.repo,
      context.headBranch,
      file.filename
    );
    results.push({ path: file.filename, content, patch: file.patch });
  }

  return results;
}

/**
 * Body for a stacked PR. Says what produced it, which PR it stacks on, and how
 * to get rid of it — the three things a maintainer who did not click the
 * checkbox themselves needs in order to judge it.
 */
function stackedBody(context: PRContext, what: string): string {
  return [
    `${what} for #${context.pullNumber}, generated by DiffSentry.`,
    "",
    `This PR is **stacked**: its base is \`${context.headBranch}\`, the head branch of #${context.pullNumber},`,
    `so merging it folds the changes into that PR rather than racing it.`,
    "",
    `Nothing was pushed to \`${context.headBranch}\`. Close this PR and delete its branch to discard the work.`,
  ].join("\n");
}

/** Everything a finishing touch needs in order to pick a destination. */
interface TouchSpec {
  /** Branch-name segment and log key. */
  touch: string;
  /** Noun phrase for the receipt: "docstrings", "unit tests", … */
  subject: string;
  /** Commit message for each file write. */
  commitMessage: string;
  /** PR title when the destination is a stacked PR. */
  prTitle: string;
  /** What the stacked PR body calls the work. */
  prSummary: string;
  /** Reply when the model produced nothing to apply. */
  emptyNote: string;
}

/** Nothing to deliver — the model returned no usable edits. */
function noEdits(): StackedPrOutcome {
  return { filesChanged: 0, failures: [] };
}

async function runTouch(
  octokit: Octokit,
  context: PRContext,
  ai: AIProvider,
  repoConfig: RepoConfig | undefined,
  delivery: Delivery,
  spec: TouchSpec,
  prompt: string,
): Promise<StackedPrOutcome> {
  const response = await ai.chat(context, prompt, repoConfig);
  const edits = parseFileEdits(response);
  if (!edits) {
    logger.warn({ touch: spec.touch }, "AI response did not contain valid file edits");
    return noEdits();
  }

  return deliver(octokit, context, edits, delivery, {
    touch: spec.touch,
    title: spec.prTitle,
    body: stackedBody(context, spec.prSummary),
    commitMessage: spec.commitMessage,
  });
}

const SPECS: Record<"docstrings" | "tests" | "simplify" | "autofix", TouchSpec> = {
  docstrings: {
    touch: "docstrings",
    subject: "docstrings",
    commitMessage: "[DiffSentry] Add docstrings",
    prTitle: "[DiffSentry] Add docstrings",
    prSummary: "Generated docstrings",
    emptyNote: "No files needed docstring updates.",
  },
  tests: {
    touch: "tests",
    subject: "unit tests",
    commitMessage: "[DiffSentry] Add unit tests",
    prTitle: "[DiffSentry] Add unit tests",
    prSummary: "Generated unit tests",
    emptyNote: "Could not generate tests for these changes.",
  },
  simplify: {
    touch: "simplify",
    subject: "simplifications",
    commitMessage: "[DiffSentry] Simplify code",
    prTitle: "[DiffSentry] Simplify code",
    prSummary: "Simplified code",
    emptyNote: "No simplification opportunities found.",
  },
  autofix: {
    touch: "autofix",
    subject: "fixes",
    commitMessage: "[DiffSentry] Auto-fix review comments",
    prTitle: "[DiffSentry] Auto-fix review comments",
    prSummary: "Fixes for the unresolved review comments",
    emptyNote: "No actionable fixes found in review comments.",
  },
};

/**
 * Render the receipt for a finishing touch. Exported so the reviewer's four
 * command branches share one formatter and none of them can drop a failure.
 */
export function formatTouchReply(
  kind: keyof typeof SPECS,
  outcome: StackedPrOutcome,
): string {
  const spec = SPECS[kind];
  return formatDeliveryReply(outcome, spec.subject, spec.emptyNote);
}

// ─── Public API ───────────────────────────────────────────────

export async function generateDocstrings(
  octokit: Octokit,
  context: PRContext,
  ai: AIProvider,
  repoConfig?: RepoConfig,
  delivery: Delivery = "branch",
): Promise<StackedPrOutcome> {
  logger.info({ pr: context.pullNumber, delivery }, "Generating docstrings for PR");

  const files = await gatherFullFiles(octokit, context);
  if (files.length === 0) return noEdits();

  const prompt = `Analyze these files and add docstrings to all functions/methods that are missing them. Return a JSON array of {path, content} where content is the full updated file. Preserve all existing code exactly. Use the appropriate docstring format for the language (JSDoc for JS/TS, Google-style for Python, etc.).

${buildFileContext(files)}`;

  return runTouch(octokit, context, ai, repoConfig, delivery, SPECS.docstrings, prompt);
}

export async function generateTests(
  octokit: Octokit,
  context: PRContext,
  ai: AIProvider,
  repoConfig?: RepoConfig,
  delivery: Delivery = "branch",
): Promise<StackedPrOutcome> {
  logger.info({ pr: context.pullNumber, delivery }, "Generating tests for PR");

  const files = await gatherFullFiles(octokit, context);
  if (files.length === 0) return noEdits();

  const prompt = `Generate comprehensive unit tests for the changed code. Return a JSON array of {path, content} where path is the test file path (e.g., tests/foo.test.ts) and content is the full test file. Use the project's existing test framework if detectable, otherwise use common defaults (Jest for JS/TS, pytest for Python).

${buildFileContext(files)}`;

  return runTouch(octokit, context, ai, repoConfig, delivery, SPECS.tests, prompt);
}

export async function simplifyCode(
  octokit: Octokit,
  context: PRContext,
  ai: AIProvider,
  repoConfig?: RepoConfig,
  delivery: Delivery = "branch",
): Promise<StackedPrOutcome> {
  logger.info({ pr: context.pullNumber, delivery }, "Simplifying code for PR");

  const files = await gatherFullFiles(octokit, context);
  if (files.length === 0) return noEdits();

  const prompt = `Review these changed files for simplification opportunities. Reduce complexity, remove dead code, simplify conditionals, consolidate duplicated logic. Do NOT change public APIs, rename exports, or alter behavior. Return a JSON array of {path, content} with the simplified files.

${buildFileContext(files)}`;

  return runTouch(octokit, context, ai, repoConfig, delivery, SPECS.simplify, prompt);
}

export async function autofix(
  octokit: Octokit,
  context: PRContext,
  ai: AIProvider,
  repoConfig?: RepoConfig,
  delivery: Delivery = "branch",
): Promise<StackedPrOutcome> {
  logger.info({ pr: context.pullNumber, delivery }, "Auto-fixing review comments for PR");

  // Fetch unresolved review comments
  let comments: { path: string; body: string; line: number | null }[];
  try {
    const { data } = await octokit.pulls.listReviewComments({
      owner: context.owner,
      repo: context.repo,
      pull_number: context.pullNumber,
    });
    comments = data
      .filter((c) => !("resolved_at" in c && c.resolved_at))
      .map((c) => ({ path: c.path, body: c.body, line: c.line ?? null }));
  } catch (err) {
    logger.warn({ err }, "Failed to fetch review comments for autofix");
    return {
      filesChanged: 0,
      failures: [],
      error: "I couldn't read the review comments on this PR, so there was nothing to fix.",
    };
  }

  if (comments.length === 0) {
    logger.info("No unresolved review comments to fix");
    return noEdits();
  }

  // Get full content for the files referenced by comments
  const affectedPaths = Array.from(new Set(comments.map((c) => c.path)));
  const files: { path: string; content: string | null; patch: string }[] = [];

  for (const filePath of affectedPaths) {
    const content = await getFileContent(
      octokit,
      context.owner,
      context.repo,
      context.headBranch,
      filePath
    );
    const fileChange = context.files.find((f) => f.filename === filePath);
    files.push({ path: filePath, content, patch: fileChange?.patch ?? "" });
  }

  const commentText = comments
    .map((c) => `- **${c.path}** (line ${c.line ?? "?"}): ${c.body}`)
    .join("\n");

  const prompt = `You are given unresolved review comments on a PR. Implement the suggested fixes. Return a JSON array of {path, content} with the fixed files.

### Unresolved Review Comments
${commentText}

### Files
${buildFileContext(files)}`;

  return runTouch(octokit, context, ai, repoConfig, delivery, SPECS.autofix, prompt);
}
