import type { WalkthroughResult, WalkthroughConfig } from "./types.js";

// ─── Helpers ──────────────────────────────────────────────────

const FILLED_CIRCLE = "\u{1F535}";
const EMPTY_CIRCLE = "\u26AA";

function effortDots(level: number): string {
  const clamped = Math.max(1, Math.min(5, Math.round(level)));
  return FILLED_CIRCLE.repeat(clamped) + EMPTY_CIRCLE.repeat(5 - clamped);
}

// ─── formatWalkthrough ────────────────────────────────────────

export function formatWalkthrough(
  result: WalkthroughResult,
  config: WalkthroughConfig,
): string {
  const sections: string[] = [];

  // Summary
  sections.push(`## Walkthrough\n\n${result.summary}`);

  // Changes table
  if (config.changed_files_summary !== false && result.fileDescriptions.length > 0) {
    const tableHeader =
      "| File | Status | Summary |\n|------|--------|---------|";
    const rows = result.fileDescriptions
      .map(
        (f) =>
          `| \`${f.filename}\` | ${f.status} | ${f.changeDescription} |`,
      )
      .join("\n");
    const table = `${tableHeader}\n${rows}`;

    let changesSection: string;
    if (result.fileDescriptions.length > 10) {
      changesSection = `## Changes\n\n<details>\n<summary>Changed files (${result.fileDescriptions.length})</summary>\n\n${table}\n\n</details>`;
    } else {
      changesSection = `## Changes\n\n${table}`;
    }
    sections.push(changesSection);
  }

  // Effort estimate
  if (
    config.estimate_effort &&
    result.effortEstimate !== undefined
  ) {
    sections.push(
      `## Estimated Review Effort\n\n${effortDots(result.effortEstimate)} (${result.effortEstimate}/5)`,
    );
  }

  // Sequence diagram
  if (config.sequence_diagrams && result.sequenceDiagram) {
    sections.push(
      `## Sequence Diagram\n\n\`\`\`mermaid\n${result.sequenceDiagram}\n\`\`\``,
    );
  }

  // Suggested labels
  if (config.suggested_labels && result.suggestedLabels?.length) {
    const labels = result.suggestedLabels.map((l) => `\`${l}\``).join(", ");
    sections.push(`## Suggested Labels\n\n${labels}`);
  }

  // Suggested reviewers
  if (config.suggested_reviewers && result.suggestedReviewers?.length) {
    const reviewers = result.suggestedReviewers
      .map((r) => (r.startsWith("@") ? r : `@${r}`))
      .join(", ");
    sections.push(`## Suggested Reviewers\n\n${reviewers}`);
  }

  // Poem
  if (config.poem && result.poem) {
    sections.push(`## Poem\n\n${result.poem}`);
  }

  // Footer
  sections.push(
    "---\n*Generated by [DiffSentry](https://github.com/mk7luke/DiffSentry)*",
  );

  let body = sections.join("\n\n");

  // Collapsible wrapper
  if (config.collapse) {
    body = `<details>\n<summary>Walkthrough</summary>\n\n${body}\n\n</details>`;
  }

  return body;
}

// ─── formatPRSummary ──────────────────────────────────────────

export function formatPRSummary(result: WalkthroughResult): string {
  const rows = result.fileDescriptions
    .map((f) => `| \`${f.filename}\` | ${f.changeDescription} |`)
    .join("\n");

  const table =
    result.fileDescriptions.length > 0
      ? `\n### Changes\n| File | Changes |\n|------|---------|${rows ? "\n" + rows : ""}`
      : "";

  return `<!-- DiffSentry Summary -->\n## Summary\n\n${result.summary}\n${table}\n<!-- End DiffSentry Summary -->`;
}

// ─── injectSummaryIntoPRBody ──────────────────────────────────

const SUMMARY_START = "<!-- DiffSentry Summary -->";
const SUMMARY_END = "<!-- End DiffSentry Summary -->";

export function injectSummaryIntoPRBody(
  existingBody: string,
  summary: string,
): string {
  const startIdx = existingBody.indexOf(SUMMARY_START);
  const endIdx = existingBody.indexOf(SUMMARY_END);

  if (startIdx !== -1 && endIdx !== -1) {
    const before = existingBody.slice(0, startIdx);
    const after = existingBody.slice(endIdx + SUMMARY_END.length);
    return before + summary + after;
  }

  if (existingBody.trim().length === 0) {
    return summary;
  }

  return `${existingBody}\n\n---\n\n${summary}`;
}
